INSERT INTO keahlian(nama) VALUES('Artificial Intelligence (AI)');
INSERT INTO keahlian(nama) VALUES('Machine Learning (ML)');
INSERT INTO keahlian(nama) VALUES('Data Science dan Big Data');
INSERT INTO keahlian(nama) VALUES('Cyber Security');
INSERT INTO keahlian(nama) VALUES('Computer Networks');
INSERT INTO keahlian(nama) VALUES('Internet of Things (IoT)');
INSERT INTO keahlian(nama) VALUES('Software Engineering');
INSERT INTO keahlian(nama) VALUES('Mobile and Web Development');
INSERT INTO keahlian(nama) VALUES('Cloud Computing');
INSERT INTO keahlian(nama) VALUES('Computer Vision');
INSERT INTO keahlian(nama) VALUES('Natural Language Processing (NLP)');
INSERT INTO keahlian(nama) VALUES('Robotics');
INSERT INTO keahlian(nama) VALUES('Human-Computer Interaction (HCI)');
INSERT INTO keahlian(nama) VALUES('Distributed Systems');
INSERT INTO keahlian(nama) VALUES('Parallel Computing');
INSERT INTO keahlian(nama) VALUES('Game Development');
INSERT INTO keahlian(nama) VALUES('Augmented Reality (AR) dan Virtual Reality (VR)');
INSERT INTO keahlian(nama) VALUES('Bioinformatics');
INSERT INTO keahlian(nama) VALUES('Embedded Systems');
INSERT INTO keahlian(nama) VALUES('Digital Forensics');
INSERT INTO keahlian(nama) VALUES('Formal Methods and Verification');
INSERT INTO keahlian(nama) VALUES('Quantum Computing');
INSERT INTO keahlian(nama) VALUES('Edge Computing');
INSERT INTO keahlian(nama) VALUES('Computational Theory');
INSERT INTO keahlian(nama) VALUES('Database Systems');
INSERT INTO keahlian(nama) VALUES('Software Testing and Quality Assurance');
INSERT INTO keahlian(nama) VALUES('E-commerce and E-business Technologies');
INSERT INTO keahlian(nama) VALUES('Multimedia Systems');
INSERT INTO keahlian(nama) VALUES('Ubiquitous Computing');
INSERT INTO keahlian(nama) VALUES('High-Performance Computing (HPC)');
INSERT INTO keahlian(nama) VALUES('Blockchain Technology');
INSERT INTO keahlian(nama) VALUES('Algorithm Design and Analysis');