const Test = () => {
    return (
        <div className="flex flex-col h-screen">
            <header className="w-full h-10 bg-black"></header>
                <div className="flex flex-grow overflow-hidden bg-slate-500">
                    <div className="w-[20%] bg-slate-300 ">
                        <h1>Test</h1>
                        <h1>Test</h1>
                        <h1>Test</h1>
                        <h1>Test</h1>
                        <h1>Test</h1>
                        <h1>Test</h1>
                    </div>
                    <div className="overflow-auto flex-1">
                    <table className="">
                        <thead>
                            <tr>
                                <th>dadj</th>
                                <th>dadj</th>
                                <th>dadj</th>
                                <th>dadj</th>
                                <th>dadj</th>
                                <th>dadj</th>
                                <th>dadj</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                            <tr>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                                <td>dadj</td>
                            </tr>
                        </tbody>
                    </table>

                    </div>
                </div>
            <footer className="w-full h-10 bg-pink-500"></footer>
        </div>
    )
}

export default Test;